routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('test_xml', 'TestXmlController@index');
Route::get('test_export_word', 'TestXmlController@test_export_word');
Route::get('test_send_mail', 'TestXmlController@test_send_mail');




//********* Backend *********//
Route::prefix('backend')->group(function () {
	Route::name('backend.')->group(function () {

		Route::get('auth/login', 'Backend\AuthController@login')->name('auth.login');
		Route::post('auth/login', 'Backend\AuthController@login_submit')->name('auth.login_submit');
		Route::get('auth/logout', 'Backend\AuthController@logout')->name('auth.logout');

		Route::middleware(['CheckAdminLogin'])->group(function () {
		    Route::get('/', 'Backend\DashboardController@index')->name('index');
		    
		    Route::resource('user', 'Backend\UserController');
		    Route::resource('partner_org', 'Backend\PartnerOrganizeController');
		    Route::resource('partner', 'Backend\PartnerController');
		    Route::get('partner/list_api/{id}', 'Backend\PartnerController@list_api')->name('partner.list_api');
		    Route::resource('dbconn', 'Backend\DatabaseConnectionController');
		    Route::post('dbconn/test_connect', 'Backend\DatabaseConnectionController@test_connect')->name('dbconn.test_connect');
		    Route::post('dbconn/list_connection', 'Backend\DatabaseConnectionController@list_connection')->name('dbconn.list_connection');
		    Route::post('dbconn/connect_by_alias', 'Backend\DatabaseConnectionController@connect_by_alias')->name('dbconn.connect_by_alias');
		    Route::resource('rest', 'Backend\RestController');
		    Route::post('rest/update_firststep/{id}', 'Backend\RestController@update_firststep')->name('rest.update_firststep');
		    Route::get('rest/{id}/step/{step}', 'Backend\RestController@step')->name('rest.step');
		    Route::post('rest/step3_save/{id}', 'Backend\RestController@step3_save')->name('rest.step3_save');
		    Route::post('rest/step4_save/{id}', 'Backend\RestController@step4_save')->name('rest.step4_save');


		    Route::resource('apilog', 'Backend\ApiLogController');
		    Route::post('apilog/export_data/{type}', 'Backend\ApiLogController@export_data')->name('apilog.export_data');
		    Route::resource('systemlog', 'Backend\SystemLogController');
		    Route::post('systemlog/export_data/{type}', 'Backend\SystemLogController@export_data')->name('systemlog.export_data');
		    Route::resource('report', 'Backend\ReportController');
		    Route::post('report/export_data/{type}', 'Backend\ReportController@export_data')->name('report.export_data');
		    Route::resource('setting', 'Backend\SettingController');


		    /**** Setting Role, Permission ****/
		    Route::resource('role', 'Backend\RoleController');
		});
	});
});

app/Http/Controllers/Backend/ApiLogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\ApiLogDataTable;
use App\ApiLog;
use Auth;

class ApiLogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ApiLogDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[7]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.log.api_log');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $log = ApiLog::findOrFail($id);

        return view('backend.log.api_list_schema', compact('log'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function export_data(Request $request)
    {
        // print_r($request->all());exit;
        header("Content-type: text/csv");
        header("Content-Disposition: attachment; filename=file.csv");
        header("Pragma: no-cache");
        header("Expires: 0");

        $logs = ApiLog::select('api_log.id', 'api_log.ip', 'api_log.path', 'api_log.partner_name', 'api_log.agent', 'api_log.status_code', 'api_log.log_type', 'api_log.datetime_at', 'api_log.datetime_at as datetime_normal');

        if( $request->seach_name )
            $logs = $logs->where('api_log.path', 'LIKE', '%'.$request->seach_name.'%');
        if( $request->seach_partner )
            $logs = $logs->where('api_log.partner_name', 'LIKE', '%'.$request->seach_partner.'%');


        if( $request->not_status_200 == 1 )
            $logs = $logs->where('api_log.status_code', '!=', '200');

        if( $request->search_status )
            $logs = $logs->where('api_log.status_code', $request->search_status);

        if( $request->search_date_start && $request->search_date_end )
            $logs = $logs->whereBetween('api_log.datetime_at', [$request->search_date_start, $request->search_date_end]);
        else if( $request->search_date_start && !$request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '>', $request->search_date_start);
        else if( !$request->search_date_start && $request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '<', $request->search_date_end);


        $logs = $logs->orderBy('api_log.datetime_at', 'desc')
                    ->get();

        $columns = array('datetime', 'status code', 'ip', 'api', 'agent', 'partner', 'type');

        $file = fopen('php://output', 'w');
        fputcsv($file, $columns);

        foreach($logs as $log) {
            fputcsv($file, array($log->datetime_at, $log->status_code, $log->ip, $log->path, $log->agent, $log->partner_name, $log->log_type));
        }
        exit();
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\User;
use Auth;

class AuthController extends Controller
{
    public function login()
    {
    	// User::create([
     //        'name' => 'asdasdsa',
     //        'email' => 'test12@gmail.com',
     //        'password' => Hash::make('test1234'),
     //    ]);
    	return view('backend.auth.login');
    }

    public function login_submit(Request $request)
    {
    	$credentials = $request->only('email', 'password');
        
        if( Auth::attempt($credentials) )
        	return redirect()->route('backend.index');
        else
        	return redirect()->back()->with('danger', 'E-mail หรือ Password ไม่ถูกต้อง');
    }

    public function logout()
    {
    	Auth::logout();
    	return redirect()->route('backend.auth.login');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ApiLog;
use Auth;

class DashboardController extends Controller
{
    public function index()
    {
        // phpinfo();exit;
        $syslog = [
            'code' => 200,
            'type' => 'view',
            'path' => 'dashboard',
            'user_id' => Auth::user()->id,
        ];
        \App\SystemLog::save_log($syslog);

    	$log_pops = ApiLog::select('api_log.path', \DB::raw('count(*) as total'), 'api_log.api_name')
                        ->where('api_log.log_type', 'req')
    					->orderBy('total', 'desc')
                        ->groupBy('api_log.path', 'api_log.api_name')
    					->limit(5)
    					->get();
    	// return $log_pop;
        $log_errors = ApiLog::select('api_log.id', 'api_log.path', 'api_log.datetime_at', 'api_log.api_name')
                        ->where('api_log.log_type', 'res')
                        ->where('api_log.status_code', '!=', '200')
                        // ->groupBy('path')
                        ->orderBy('api_log.datetime_at', 'desc')
                        ->limit(5)
                        ->get();
        // return $log_errors;
        $report = ApiLog::select('api_log.path', 'api_log.api_name', \DB::raw('count(*) as total'))
                        ->where('api_log.log_type', 'req')
                        ->where('api_log.path', '!=', 'auth/login')
                        ->groupBy('api_log.path', 'api_log.api_name')
                        ->limit(20)
                        ->get();
        // return $report;

    	return view('backend.index', compact('log_pops', 'log_errors', 'report'));
    }
}

app/Http/Controllers/Backend/PartnerOrganizeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\PartnerOrganizeDataTable;
use App\ApiCategory;
use Auth;

class PartnerOrganizeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PartnerOrganizeDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.partner_org.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->create ){

            $syslog = [
                'code' => 401,
                'type' => 'insert',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        return view('backend.partner_org.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $validatedData = $request->validate([
            'cat_name' => 'required|unique:api_category',
        ]);

        $cat = new ApiCategory;
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'insert',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Create partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->route('backend.partner_org.index')->with('message', 'Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->edit ){

            $syslog = [
                'code' => 401,
                'type' => 'update',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        $cat = ApiCategory::findOrFail($id);

        return view('backend.partner_org.edit', compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cat = ApiCategory::findOrFail($id);
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'update',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Update partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->back()->with('message', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat = ApiCategory::findOrFail($id);

        $syslog = [
            'code' => 200,
            'type' => 'delete',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Delete partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        foreach( $cat->partner as $row ){
            $row->delete();
        }

        $cat->delete();

        return redirect()->route('backend.partner_org.index')->with('message', 'Deleted');
    }
}

resources/views/backend/rest/create.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<style>

</style>
@endpush

@section('content')
<div class="section-header">
	<h2>Create Schema</h2>
</div>

<div class="card">
	<div class="card-body">

		@include('layouts.errors')

		<form method="post" action="javascript:" id="form_db_connect">
			@csrf
			
			@include('backend.rest.form1')

			<!-- <div class="text-right">
				<a href="{{ route('backend.rest.index') }}" class="btn btn-secondary btn_form">Cancel</a>
				&nbsp;
				<button type="submit" class="btn btn_pink btn_form btn_dbconnect_default">Save</button>
				<button type="submit" class="btn btn_pink btn_form btn_dbconnect_loading" style="display:none;"><i class="fa fa-refresh fa-spin fa-fw"></i></button>
			</div> -->
		</form>

	</div>
</div>
@endsection

resources/views/backend/rest/form1.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<style>
/*#step2_domain_span{display:inline-block; width:200px; vertical-align:middle;}
input[name=api_url_schema]{display:inline-block; width:calc(100% - 200px);}*/
#step2_domain_span{display:inline-block; width:auto; vertical-align:middle;}
input[name=api_url_schema]{display:inline-block; width:300px; vertical-align:middle;}
</style>
@endpush

@section('content')
<div class="section-header">
	<h2>Create Schema</h2>
</div>

<form method="post" action="javascript:" id="form_rest" class="card noedge">
	
	<?php
	$page_step = 1;
	if( @$step ) 
		$page_step = @$step;
	?>
	@include('backend.rest.nav_step', ['step' => $page_step])

	<div class="card-body" style="padding-bottom:0;">
		@include('layouts.errors')
		<div id="ajax_validate"></div>
	</div>

	<div class="card-body" id="form_step1" style="display:none;">

		<div>
			@csrf

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Database type :</label>
				<div class="col-sm-10">
			    	<select class="form-control" id="conn_type">
			    		<option>-- Database type --</option>
			    		<option value="mysql" {{ @$dbconn->conn_type=='mysql'? 'selected':'' }}>MySQL</option>
			    		<option value="sqlsrv" {{ @$dbconn->conn_type=='sqlsrv'? 'selected':'' }}>MSSQL</option>
			    		<option value="oracle" {{ @$dbconn->conn_type=='oracle'? 'selected':'' }}>Oracle</option>
			    	</select>
			    </div>
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Choose database connection :</label>
				<div class="col-sm-10">
			    	<select class="form-control" name="conn_alias">
			    		<option value>-- Choose Connection --</option>
			    	</select>
			    </div>
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label"></label>
				<div class="col-sm-10">
			    	<button type="button" class="btn btn-primary btn_test_connect">Connected</button>
			    	<button type="button" class="btn btn-primary btn_connect_loading" style="display:none;"><i class="fa fa-refresh fa-spin fa-fw"></i></button>
			    	&nbsp;
			    	<span class="conenct_status"></span>
			    </div>
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Choose Table :</label>
				<div class="col-sm-10">
			    	<select class="form-control" name="conn_table">
			    		<option value>-- Choose Table --</option>
			    	</select>
			    </div>
			</div>


			<!-- <div class="text-right">
				<a href="{{ route('backend.rest.index') }}" class="btn btn-secondary btn_form">Cancel</a>
				&nbsp;
				<button type="submit" class="btn btn_pink btn_form btn_dbconnect_default">Save</button>
				<button type="submit" class="btn btn_pink btn_form btn_dbconnect_loading" style="display:none;"><i class="fa fa-refresh fa-spin fa-fw"></i></button>
			</div> -->
		</div>

	</div>


	
	<div class="card-body" id="form_step2" style="display:none;">
		
		<div class="form-group row label_status">
			<label class="col-sm-2 col-form-label">Authentication : </label>
			<div class="col-sm-10">
				<?php
				$checked = 'public';
				if( @$rest->api_type == 'private' )
					$checked = 'private';
				?>
		    	<label>
		    		<input type="radio" name="api_type" value="public" {{ $checked=='public'? 'checked':'' }}>
		    		Public API
		    	</label>
		    	&nbsp;
		    	<label>
		    		<input type="radio" name="api_type" value="private" {{ $checked=='private'? 'checked':'' }}>
		    		Private API
		    	</label>
		    </div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label">API name :</label>
			<div class="col-sm-10">
		    	<input type="text" class="form-control" name="api_name" value="{{ @$rest->api_name }}">
		    </div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label">API URL :</label>
			<div class="col-sm-10">
		    	{{-- <span id="step2_domain_span">https://apijfo.moj.go.th/api/</span><input type="text" class="form-control api_str" name="api_url_schema" value="{{ @$rest->api_url_schema }}" {{ @$rest->id? 'disabled':'' }}> --}}

		    	<span>{{ asset('') }}api/</span>
		    	<input type="text" class="form-control api_str" name="api_url_schema" value="{{ @$rest->api_url_schema }}" {{ @$rest->id? 'disabled':'' }}>
		    </div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Description :</label>
			<div class="col-sm-10">
		    	<textarea class="form-control" name="api_description" rows="4">{{ @$rest->api_description }}</textarea>
		    </div>
		</div>

		<?php
		$checked = 1;
		if( isset($rest->status) && $rest->status == 0 )
			$checked = 0;
		?>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Status :</label>
			<div class="col-sm-10">
		    	<label>
		    		<input type="radio" name="status" value="1" {{ $checked==1? 'checked':'' }}>
		    		Enable
		    	</label>
				&nbsp; &nbsp; &nbsp;
		    	<label>
		    		<input type="radio" name="status" value="0" {{ $checked==0? 'checked':'' }}>
		    		disable
		    	</label>
		    </div>
		</div>

	</div>

	<div class="card-footer btn_step1" style="display:none;">
		<a href="{{ route('backend.rest.index') }}" class="btn btn-secondary btn_form">Cancel</a>
		<div class="pull-right">
			<button type="button" class="btn btn_pink btn_form btn_submit1">Next</button>
		</div>
	</div>

	<div class="card-footer btn_step2" style="display:none;">
		<button type="button" class="btn btn-secondary btn_form backto_step1">Cancel</button>
		<div class="pull-right">
			<button type="button" class="btn btn_pink btn_form btn_submit2">Next</button>
			<button type="button" class="btn btn_pink btn_form btn_loading2" style="display:none;"><i class="fa fa-refresh fa-spin fa-fw"></i></button>
		</div>
	</div>

</form>
@endsection

@push('add_js')
<script>

$(document).ready(function(){


if( '{{ @$step }}' == '2' ){
	$('#form_step1, .btn_step1').hide();
	$('#form_step2, .btn_step2').show();
}else{
	$('#form_step1, .btn_step1').show();
	$('#form_step2, .btn_step2').hide();
}


// Edit
@if( @$dbconn->id )

set_connect();
async function set_connect()
{
	await list_connection();
	await $('select[name=conn_alias]').val('{{ @$rest->conn_alias }}');

	$('.btn_test_connect').hide();
	$('.btn_connect_loading').show();

	await list_tables();
	$('.btn_test_connect').show();
	$('.btn_connect_loading').hide();

	$('select[name=conn_table]').val('{{ @$rest->conn_table }}');
}
@endif
// End Edit



$('#conn_type').change(function(){
	list_connection();

	let conn = "<option value>Choose Connection</option>";
	$('select[name=conn_alias]').html(conn);

	let tb = "<option value>Choose Table</option>";
	$('select[name=conn_table]').html(tb);
	$('.conenct_status').html('');
});

async function list_connection()
{
	await $.ajax({
		headers: {
	        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
	    },
		type: 'post',
		url: "{{ route('backend.dbconn.list_connection') }}",
		data: {user_id: "{{ Auth::user()->id }}", conn_type: $('#conn_type').val()},
		success: function(res)
		{
			console.log(res);
			let html = '';
			if( res.length > 0 ){
				$.each(res, function(index, val){
					html += "<option value='"+val.conn_alias+"'>"+val.conn_name+"</option>";
				});
			}else{
				html = "<option value>Choose Connection</option>";
			}

			$("select[name=conn_alias]").html(html);
		}
	});
}


$("select[name=conn_alias]").change(function(){
	let html = "<option value>Choose Table</option>";
	$('select[name=conn_table]').html(html);
	$('.conenct_status').html('');
});

$('.btn_test_connect').click(async function(){
	
	if( $("select[name=conn_alias]").val() == '' ){
		swal({
			type: 'warning',
			title: 'Please select Connection.',
		});
		return false;
	}

	$('.btn_test_connect').hide();
	$('.btn_connect_loading').show();

	await list_tables();
	$('.btn_test_connect').show();
	$('.btn_connect_loading').hide();
});

async function list_tables()
{
	$('.btn_submit2').hide();
	$('.btn_loading2').show();

	await $.ajax({
		headers: {
	        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
	    },
		type: 'post',
		url: "{{ route('backend.dbconn.connect_by_alias') }}",
		data: {conn_alias: $("select[name=conn_alias]").val()},
		success: function(res)
		{
			console.log(res);
			$('.btn_submit2').show();
			$('.btn_loading2').hide();
			
			if( res.status == 'success' ){

				$('.conenct_status').html("<span class='text-success'>Connect success !</span>");
				let html = '';
				if( res.tables.length == 0 ){
					html += "<option value>-- Choose Table --</option>";
				}else{
					$.each(res.tables, function(index, val){
						html += "<option value='"+val+"'>"+val+"</option>";
					});
				}

				$("select[name=conn_table]").html(html);

			}else{
				swal({
					type: 'error',
					title: 'Error',
					text: res.msg,
				});
				$('.conenct_status').html("<span class='text-danger'>Connection fail !</span>");
			}

		},
		error: function (jqXHR, exception)
	    {
	    	$('.btn_submit2').show();
			$('.btn_loading2').hide();

	        let msg = set_ajax_error(jqXHR, exception);
	        swal({
				type: 'error',
				title: 'Error',
				text: msg,
			});
	    },
	});
}



$('.btn_submit1').click(function(){

	var conn_table = $("select[name=conn_table]");
	if( conn_table.val().trim() == '' ){
		swal({
			type: 'warning',
			title: 'Warning',
			text: 'Please Choose Table',
		});
	}else{

		$("#form_step1, .btn_step1").hide();

		$('.step2').addClass('step_active');
		$("#form_step2, .btn_step2").show();
	}
});

$('.backto_step1').click(function(){
	$("#form_step1, .btn_step1").show();
	$('.step2').removeClass('step_active');
	$("#form_step2, .btn_step2").hide();
});



$('.btn_submit2').click(async function(){

	@if( @$rest->schema_req_markup )
		let status = await Swal.fire({
			type: "warning",
			title: 'Wraning',
			text: 'ข้อมูล step 3 และ 4 จะหายไป ยืนยันหรือไม่',
			showCancelButton: true,
			confirmButtonText: 'Confirm'
		})
		.then((res)=>{
			if ( res.value ){
				return true;
			}else{
				return false;
			}
		});

		if( status == false ){
			return false;
		}
	@endif

	$('.btn_submit2').hide();
	$('.btn_loading2').show();

	var formData = new FormData($("#form_rest")[0]);
	@if( @$rest->id )
	let url = "{{ route('backend.rest.update_firststep', $rest->id) }}";
	@else
	let url = "{{ route('backend.rest.store') }}";
	@endif


	$.ajax({
		headers: {
	        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
	    },
		type: 'post',
		url: url,
		data: formData,
		processData: false,
		contentType: false,
		success: function(res)
		{
			// console.log(res);
			$('.btn_submit2').show();
			$('.btn_loading2').hide();

			if( res.status == 'success' ){
				swal({
					type: "success",
					title: 'Success',
					text: 'API Schema Created.',
				})
				.then(function(){
					window.location.href = res.url;
				});

			}else{
				var html = html_alert(res.data);
				$('#ajax_validate').html(html);
			}
		},
		error: function (jqXHR, exception)
	    {
	    	$('.btn_submit2').show();
			$('.btn_loading2').hide();
	        let msg = set_ajax_error(jqXHR, exception);
	        swal({
				type: 'error',
				title: 'Error',
				text: msg,
			});
	    },
	});
});

});

</script>
@endpush