routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('test_xml', 'TestXmlController@index');
Route::get('test_export_word', 'TestXmlController@test_export_word');
Route::get('test_send_mail', 'TestXmlController@test_send_mail');




//********* Backend *********//
Route::prefix('backend')->group(function () {
	Route::name('backend.')->group(function () {

		Route::get('auth/login', 'Backend\AuthController@login')->name('auth.login');
		Route::post('auth/login', 'Backend\AuthController@login_submit')->name('auth.login_submit');
		Route::get('auth/logout', 'Backend\AuthController@logout')->name('auth.logout');

		Route::middleware(['CheckAdminLogin'])->group(function () {
		    Route::get('/', 'Backend\DashboardController@index')->name('index');
		    
		    Route::resource('user', 'Backend\UserController');
		    Route::resource('partner_org', 'Backend\PartnerOrganizeController');
		    Route::resource('partner', 'Backend\PartnerController');
		    Route::get('partner/list_api/{id}', 'Backend\PartnerController@list_api')->name('partner.list_api');
		    Route::resource('dbconn', 'Backend\DatabaseConnectionController');
		    Route::post('dbconn/test_connect', 'Backend\DatabaseConnectionController@test_connect')->name('dbconn.test_connect');
		    Route::post('dbconn/list_connection', 'Backend\DatabaseConnectionController@list_connection')->name('dbconn.list_connection');
		    Route::post('dbconn/connect_by_alias', 'Backend\DatabaseConnectionController@connect_by_alias')->name('dbconn.connect_by_alias');
		    Route::resource('rest', 'Backend\RestController');
		    Route::post('rest/update_firststep/{id}', 'Backend\RestController@update_firststep')->name('rest.update_firststep');
		    Route::get('rest/{id}/step/{step}', 'Backend\RestController@step')->name('rest.step');
		    Route::post('rest/step3_save/{id}', 'Backend\RestController@step3_save')->name('rest.step3_save');
		    Route::post('rest/step4_save/{id}', 'Backend\RestController@step4_save')->name('rest.step4_save');


		    Route::resource('apilog', 'Backend\ApiLogController');
		    Route::post('apilog/export_data/{type}', 'Backend\ApiLogController@export_data')->name('apilog.export_data');
		    Route::resource('systemlog', 'Backend\SystemLogController');
		    Route::post('systemlog/export_data/{type}', 'Backend\SystemLogController@export_data')->name('systemlog.export_data');
		    Route::resource('report', 'Backend\ReportController');
		    Route::post('report/export_data/{type}', 'Backend\ReportController@export_data')->name('report.export_data');
		    Route::resource('setting', 'Backend\SettingController');


		    /**** Setting Role, Permission ****/
		    Route::resource('role', 'Backend\RoleController');
		});
	});
});

app/Http/Controllers/Backend/ApiLogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\ApiLogDataTable;
use App\ApiLog;
use Auth;

class ApiLogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ApiLogDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[7]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.log.api_log');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $log = ApiLog::findOrFail($id);

        return view('backend.log.api_list_schema', compact('log'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function export_data(Request $request)
    {
        // print_r($request->all());exit;
        header("Content-type: text/csv");
        header("Content-Disposition: attachment; filename=file.csv");
        header("Pragma: no-cache");
        header("Expires: 0");

        $logs = ApiLog::select('api_log.id', 'api_log.ip', 'api_log.path', 'api_log.partner_name', 'api_log.agent', 'api_log.status_code', 'api_log.log_type', 'api_log.datetime_at', 'api_log.datetime_at as datetime_normal');

        if( $request->seach_name )
            $logs = $logs->where('api_log.path', 'LIKE', '%'.$request->seach_name.'%');
        if( $request->seach_partner )
            $logs = $logs->where('api_log.partner_name', 'LIKE', '%'.$request->seach_partner.'%');


        if( $request->not_status_200 == 1 )
            $logs = $logs->where('api_log.status_code', '!=', '200');

        if( $request->search_status )
            $logs = $logs->where('api_log.status_code', $request->search_status);

        if( $request->search_date_start && $request->search_date_end )
            $logs = $logs->whereBetween('api_log.datetime_at', [$request->search_date_start, $request->search_date_end]);
        else if( $request->search_date_start && !$request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '>', $request->search_date_start);
        else if( !$request->search_date_start && $request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '<', $request->search_date_end);


        $logs = $logs->orderBy('api_log.datetime_at', 'desc')
                    ->get();

        $columns = array('datetime', 'status code', 'ip', 'api', 'agent', 'partner', 'type');

        $file = fopen('php://output', 'w');
        fputcsv($file, $columns);

        foreach($logs as $log) {
            fputcsv($file, array($log->datetime_at, $log->status_code, $log->ip, $log->path, $log->agent, $log->partner_name, $log->log_type));
        }
        exit();
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\User;
use Auth;

class AuthController extends Controller
{
    public function login()
    {
    	// User::create([
     //        'name' => 'asdasdsa',
     //        'email' => 'test12@gmail.com',
     //        'password' => Hash::make('test1234'),
     //    ]);
    	return view('backend.auth.login');
    }

    public function login_submit(Request $request)
    {
    	$credentials = $request->only('email', 'password');
        
        if( Auth::attempt($credentials) )
        	return redirect()->route('backend.index');
        else
        	return redirect()->back()->with('danger', 'E-mail หรือ Password ไม่ถูกต้อง');
    }

    public function logout()
    {
    	Auth::logout();
    	return redirect()->route('backend.auth.login');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ApiLog;
use Auth;

class DashboardController extends Controller
{
    public function index()
    {
        // phpinfo();exit;
        $syslog = [
            'code' => 200,
            'type' => 'view',
            'path' => 'dashboard',
            'user_id' => Auth::user()->id,
        ];
        \App\SystemLog::save_log($syslog);

    	$log_pops = ApiLog::select('api_log.path', \DB::raw('count(*) as total'), 'api_log.api_name')
                        ->where('api_log.log_type', 'req')
    					->orderBy('total', 'desc')
                        ->groupBy('api_log.path', 'api_log.api_name')
    					->limit(5)
    					->get();
    	// return $log_pop;
        $log_errors = ApiLog::select('api_log.id', 'api_log.path', 'api_log.datetime_at', 'api_log.api_name')
                        ->where('api_log.log_type', 'res')
                        ->where('api_log.status_code', '!=', '200')
                        // ->groupBy('path')
                        ->orderBy('api_log.datetime_at', 'desc')
                        ->limit(5)
                        ->get();
        // return $log_errors;
        $report = ApiLog::select('api_log.path', 'api_log.api_name', \DB::raw('count(*) as total'))
                        ->where('api_log.log_type', 'req')
                        ->where('api_log.path', '!=', 'auth/login')
                        ->groupBy('api_log.path', 'api_log.api_name')
                        ->limit(20)
                        ->get();
        // return $report;

    	return view('backend.index', compact('log_pops', 'log_errors', 'report'));
    }
}

app/Http/Controllers/Backend/PartnerOrganizeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\PartnerOrganizeDataTable;
use App\ApiCategory;
use Auth;

class PartnerOrganizeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PartnerOrganizeDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.partner_org.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->create ){

            $syslog = [
                'code' => 401,
                'type' => 'insert',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        return view('backend.partner_org.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $validatedData = $request->validate([
            'cat_name' => 'required|unique:api_category',
        ]);

        $cat = new ApiCategory;
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'insert',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Create partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->route('backend.partner_org.index')->with('message', 'Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->edit ){

            $syslog = [
                'code' => 401,
                'type' => 'update',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        $cat = ApiCategory::findOrFail($id);

        return view('backend.partner_org.edit', compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cat = ApiCategory::findOrFail($id);
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'update',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Update partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->back()->with('message', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat = ApiCategory::findOrFail($id);

        $syslog = [
            'code' => 200,
            'type' => 'delete',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Delete partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        foreach( $cat->partner as $row ){
            $row->delete();
        }

        $cat->delete();

        return redirect()->route('backend.partner_org.index')->with('message', 'Deleted');
    }
}

resources/views/backend/layouts/backend.blade.php
@extends("layouts/frame")


@section('frame')

<?php
$user = Auth::user();
?>
<div class="wrapper boxed-wrapper">
  <header class="main-header"> 
    <a href="{{ route('backend.index') }}" class="logo blue-bg"> 
        <!-- <span class="logo-mini">
            <img src="{{ asset('images/no_img.jpg') }}" alt="">
        </span> 
        
        <span class="logo-lg">
            <img src="{{ asset('images/no_img.jpg') }}" alt="">
        </span> -->
        JFO API Gateway
    </a> 
    
    <nav class="navbar blue-bg navbar-static-top"> 
      
      <ul class="nav navbar-nav pull-left">
        <li><a class="sidebar-toggle" data-toggle="push-menu" href=""></a> </li>
      </ul>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-envelope-o"></i></a>
            <ul class="dropdown-menu">
              <li class="header">ล่าสุด</li>
              <li>
                <ul class="menu">
                    <li>
	                    <a href="">
	                      <div class="pull-left">
	                        <img src="{{ asset('images/no_img.jpg') }}" class="img-circle" alt="User Image">
	                      </div>
	                      <h4>ชื่อทดสอบ</h4>
	                      <p>ผู้สมัครได้ส่งคำร้องสมัครสมาชิก</p>
	                      <p><span class="time">10/09/2019 00:22:55</span></p>
	                    </a>
 					          </li>
                </ul>
              </li>
              <li class="footer"><a href="">View All Messages</a></li>
            </ul>
          </li> -->

          <li class="dropdown user user-menu p-ph-res"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img src="{{ asset('images/no_img.jpg') }}" class="user-image" alt="User Image"> <span class="hidden-xs">{{ $user->firstname }}</span> </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <div class="pull-left user-img"><img src="{{ asset('images/no_img.jpg') }}" class="img-responsive" alt="User"></div>
                <p class="text-left">{{ $user->firstname }} <small>{{ $user->email }}</small> </p>
                <!-- <div class="view-link text-left"><a href="#">View Profile</a> </div> -->
              </li>
              <!-- <li><a href="#"><i class="icon-profile-male"></i> My Profile</a></li> -->
              <!-- <li><a href="#"><i class="icon-wallet"></i> My Balance</a></li> -->
              <!-- <li><a href="#"><i class="icon-envelope"></i> Inbox</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#"><i class="icon-gears"></i> Account Setting</a></li> -->
              <li role="separator" class="divider"></li>
              <li><a href="{{ route('backend.auth.logout') }}"><i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar"> 
    <!-- sidebar: style can be found in sidebar.less -->
    <div class="sidebar"> 
      <!-- Sidebar user panel -->
      <!-- {{-- <div class="user-panel">
        <div class="image text-center"><img src="{{ asset('images/no_img.jpg') }}" class="img-circle" alt="User Image"> </div>
        <div class="info">
          <p>OFza123</p>
          <a href="{{ asset('') }}"><i class="fa fa-home"></i></a>
          <a href=""><i class="fa fa-power-off"></i></a>
      	</div>
      </div> --}} -->
      
      <?php
      $perms = \App\Perm::can();
      ?>
      <ul class="sidebar-menu" data-widget="tree">
        <!-- <li class="header">Menu</li> -->

        @if( @$perms[1]->view )
        <li><a href="{{ route('backend.index') }}"><i class="fa fa-tachometer"></i> Dashboard</a> </li>
        @endif

        @if( @$perms[2]->view || @$perms[11]->view  )
        <?php
        $active = '';
        if( Request::segment(2) == 'user' || Request::segment(2) == 'role' )
            $active = 'active';
        ?>
        <li class="treeview {{ $active }}"> <a href="#"> <i class="fa fa-user"></i> <span>User</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
            <ul class="treeview-menu">
                @if( @$perms[2]->view )
                <li class="{{ Request::segment(2)=='user'?'active':'' }}"><a href="{{ route('backend.user.index') }}">User</a></li>
                @endif
                @if( @$perms[11]->view )
                <li class="{{ Request::segment(2)=='role'?'active':'' }}"><a href="{{ route('backend.role.index') }}">Roles & Permission</a></li>
                @endif
            </ul>
        </li>
        @endif

        
        @if( @$perms[9]->view || @$perms[3]->view  )
        <?php
        $active = '';
        if( Request::segment(2) == 'partner_org' || Request::segment(2) == 'partner' )
            $active = 'active';
        ?>
        <li class="treeview {{ $active }}"> <a href="#"> <i class="fa fa-user-circle-o"></i> <span>Partner</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
            <ul class="treeview-menu">
              @if( @$perms[9]->view )
              <li class="{{ Request::segment(2)=='partner_org'?'active':'' }}"><a href="{{ route('backend.partner_org.index') }}">Partner Organization</a></li>
              @endif
              @if( @$perms[3]->view )
              <li class="{{ Request::segment(2)=='partner'?'active':'' }}"><a href="{{ route('backend.partner.index') }}">Partner</a></li>
              @endif
            </ul>
        </li>
        @endif


        @if( @$perms[4]->view )
        <li><a href="{{ route('backend.dbconn.index') }}"><i class="fa fa-database"></i> Database Connection</a> </li>
        @endif

        @if( @$perms[5]->view )
        <li><a href="{{ route('backend.rest.index') }}"><i class="fa fa-plane"></i> API</a> </li>
        @endif

        @if( @$perms[7]->view )
        <?php
        $active = '';
        if( Request::segment(2) == 'apilog' )
            $active = 'active';
        ?>
        <li class="treeview {{ $active }}"> <a href="#"> <i class="fa fa-table"></i> <span>Log</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
            <ul class="treeview-menu">
                <li class="{{ request::segment(2)=='apilog'&&@request()->input('log_type')!='error'?'active':'' }}"><a href="{{ route('backend.apilog.index') }}">API Log</a></li>
                <li class="{{ request::segment(2)=='apilog'&&@request()->input('log_type')=='error'?'active':'' }}"><a href="{{ route('backend.apilog.index') }}?log_type=error">API Error Log</a></li>
            </ul>
        </li>
        @endif

        @if( @$perms[10]->view )
        <li><a href="{{ route('backend.systemlog.index') }}"><i class="fa fa-table"></i> System Log</a> </li>
        @endif

        @if( @$perms[6]->view )
        <li><a href="{{ route('backend.report.index') }}"><i class="fa fa-table"></i> Report</a> </li>
        @endif

        @if( @$perms[8]->view )
        <li><a href="{{ route('backend.setting.index') }}"><i class="fa fa-cog"></i> Setting</a> </li>
        @endif

        

        
        <!-- <li class="treeview"> <a href="#"> <i class="fa fa-cog"></i> <span>ตั้งค่า</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
          	<ul class="treeview-menu">
	            <li><a href="{{ route('backend.role.index') }}">Roles & Permission</a></li>
          	</ul>
	       </li> -->
        

        
      </ul>

    </div>
    <!-- /.sidebar --> 
  </aside>
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper"> 

    <!-- Main content -->
    <div class="content"> 
        
        @yield('content')
		
    </div>
    <!-- /.content --> 
  </div>

  <!-- /.content-wrapper -->
  <!-- <footer class="main-footer">
    <div class="pull-right hidden-xs">Version 1.2</div>
    Copyright © 2017 API-Project. All rights reserved.
  </footer> -->
</div>

@endsection