routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('test_xml', 'TestXmlController@index');
Route::get('test_export_word', 'TestXmlController@test_export_word');
Route::get('test_send_mail', 'TestXmlController@test_send_mail');




//********* Backend *********//
Route::prefix('backend')->group(function () {
	Route::name('backend.')->group(function () {

		Route::get('auth/login', 'Backend\AuthController@login')->name('auth.login');
		Route::post('auth/login', 'Backend\AuthController@login_submit')->name('auth.login_submit');
		Route::get('auth/logout', 'Backend\AuthController@logout')->name('auth.logout');

		Route::middleware(['CheckAdminLogin'])->group(function () {
		    Route::get('/', 'Backend\DashboardController@index')->name('index');
		    
		    Route::resource('user', 'Backend\UserController');
		    Route::resource('partner_org', 'Backend\PartnerOrganizeController');
		    Route::resource('partner', 'Backend\PartnerController');
		    Route::get('partner/list_api/{id}', 'Backend\PartnerController@list_api')->name('partner.list_api');
		    Route::resource('dbconn', 'Backend\DatabaseConnectionController');
		    Route::post('dbconn/test_connect', 'Backend\DatabaseConnectionController@test_connect')->name('dbconn.test_connect');
		    Route::post('dbconn/list_connection', 'Backend\DatabaseConnectionController@list_connection')->name('dbconn.list_connection');
		    Route::post('dbconn/connect_by_alias', 'Backend\DatabaseConnectionController@connect_by_alias')->name('dbconn.connect_by_alias');
		    Route::resource('rest', 'Backend\RestController');
		    Route::post('rest/update_firststep/{id}', 'Backend\RestController@update_firststep')->name('rest.update_firststep');
		    Route::get('rest/{id}/step/{step}', 'Backend\RestController@step')->name('rest.step');
		    Route::post('rest/step3_save/{id}', 'Backend\RestController@step3_save')->name('rest.step3_save');
		    Route::post('rest/step4_save/{id}', 'Backend\RestController@step4_save')->name('rest.step4_save');


		    Route::resource('apilog', 'Backend\ApiLogController');
		    Route::post('apilog/export_data/{type}', 'Backend\ApiLogController@export_data')->name('apilog.export_data');
		    Route::resource('systemlog', 'Backend\SystemLogController');
		    Route::post('systemlog/export_data/{type}', 'Backend\SystemLogController@export_data')->name('systemlog.export_data');
		    Route::resource('report', 'Backend\ReportController');
		    Route::post('report/export_data/{type}', 'Backend\ReportController@export_data')->name('report.export_data');
		    Route::resource('setting', 'Backend\SettingController');


		    /**** Setting Role, Permission ****/
		    Route::resource('role', 'Backend\RoleController');
		});
	});
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name', 'status'];

    public function perms()
    {
    	return $this->hasMany('App\Perm', 'role_id', 'id');
    }
}

app/Http/Controllers/Backend/ApiLogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\ApiLogDataTable;
use App\ApiLog;
use Auth;

class ApiLogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ApiLogDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[7]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.log.api_log');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $log = ApiLog::findOrFail($id);

        return view('backend.log.api_list_schema', compact('log'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function export_data(Request $request)
    {
        // print_r($request->all());exit;
        header("Content-type: text/csv");
        header("Content-Disposition: attachment; filename=file.csv");
        header("Pragma: no-cache");
        header("Expires: 0");

        $logs = ApiLog::select('api_log.id', 'api_log.ip', 'api_log.path', 'api_log.partner_name', 'api_log.agent', 'api_log.status_code', 'api_log.log_type', 'api_log.datetime_at', 'api_log.datetime_at as datetime_normal');

        if( $request->seach_name )
            $logs = $logs->where('api_log.path', 'LIKE', '%'.$request->seach_name.'%');
        if( $request->seach_partner )
            $logs = $logs->where('api_log.partner_name', 'LIKE', '%'.$request->seach_partner.'%');


        if( $request->not_status_200 == 1 )
            $logs = $logs->where('api_log.status_code', '!=', '200');

        if( $request->search_status )
            $logs = $logs->where('api_log.status_code', $request->search_status);

        if( $request->search_date_start && $request->search_date_end )
            $logs = $logs->whereBetween('api_log.datetime_at', [$request->search_date_start, $request->search_date_end]);
        else if( $request->search_date_start && !$request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '>', $request->search_date_start);
        else if( !$request->search_date_start && $request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '<', $request->search_date_end);


        $logs = $logs->orderBy('api_log.datetime_at', 'desc')
                    ->get();

        $columns = array('datetime', 'status code', 'ip', 'api', 'agent', 'partner', 'type');

        $file = fopen('php://output', 'w');
        fputcsv($file, $columns);

        foreach($logs as $log) {
            fputcsv($file, array($log->datetime_at, $log->status_code, $log->ip, $log->path, $log->agent, $log->partner_name, $log->log_type));
        }
        exit();
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\User;
use Auth;

class AuthController extends Controller
{
    public function login()
    {
    	// User::create([
     //        'name' => 'asdasdsa',
     //        'email' => 'test12@gmail.com',
     //        'password' => Hash::make('test1234'),
     //    ]);
    	return view('backend.auth.login');
    }

    public function login_submit(Request $request)
    {
    	$credentials = $request->only('email', 'password');
        
        if( Auth::attempt($credentials) )
        	return redirect()->route('backend.index');
        else
        	return redirect()->back()->with('danger', 'E-mail หรือ Password ไม่ถูกต้อง');
    }

    public function logout()
    {
    	Auth::logout();
    	return redirect()->route('backend.auth.login');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ApiLog;
use Auth;

class DashboardController extends Controller
{
    public function index()
    {
        // phpinfo();exit;
        $syslog = [
            'code' => 200,
            'type' => 'view',
            'path' => 'dashboard',
            'user_id' => Auth::user()->id,
        ];
        \App\SystemLog::save_log($syslog);

    	$log_pops = ApiLog::select('api_log.path', \DB::raw('count(*) as total'), 'api_log.api_name')
                        ->where('api_log.log_type', 'req')
    					->orderBy('total', 'desc')
                        ->groupBy('api_log.path', 'api_log.api_name')
    					->limit(5)
    					->get();
    	// return $log_pop;
        $log_errors = ApiLog::select('api_log.id', 'api_log.path', 'api_log.datetime_at', 'api_log.api_name')
                        ->where('api_log.log_type', 'res')
                        ->where('api_log.status_code', '!=', '200')
                        // ->groupBy('path')
                        ->orderBy('api_log.datetime_at', 'desc')
                        ->limit(5)
                        ->get();
        // return $log_errors;
        $report = ApiLog::select('api_log.path', 'api_log.api_name', \DB::raw('count(*) as total'))
                        ->where('api_log.log_type', 'req')
                        ->where('api_log.path', '!=', 'auth/login')
                        ->groupBy('api_log.path', 'api_log.api_name')
                        ->limit(20)
                        ->get();
        // return $report;

    	return view('backend.index', compact('log_pops', 'log_errors', 'report'));
    }
}

app/Http/Controllers/Backend/PartnerOrganizeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\PartnerOrganizeDataTable;
use App\ApiCategory;
use Auth;

class PartnerOrganizeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PartnerOrganizeDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.partner_org.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->create ){

            $syslog = [
                'code' => 401,
                'type' => 'insert',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        return view('backend.partner_org.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $validatedData = $request->validate([
            'cat_name' => 'required|unique:api_category',
        ]);

        $cat = new ApiCategory;
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'insert',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Create partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->route('backend.partner_org.index')->with('message', 'Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->edit ){

            $syslog = [
                'code' => 401,
                'type' => 'update',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        $cat = ApiCategory::findOrFail($id);

        return view('backend.partner_org.edit', compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cat = ApiCategory::findOrFail($id);
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'update',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Update partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->back()->with('message', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat = ApiCategory::findOrFail($id);

        $syslog = [
            'code' => 200,
            'type' => 'delete',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Delete partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        foreach( $cat->partner as $row ){
            $row->delete();
        }

        $cat->delete();

        return redirect()->route('backend.partner_org.index')->with('message', 'Deleted');
    }
}

resources/views/backend/role/create.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<style>

</style>
@endpush

@section('content')
<div class="section-header">
	<h2>Create Role & Permission</h2>
</div>

<div class="card">
	<div class="card-body">

		@include('layouts.errors')

		<form method="post" action="{{ route('backend.role.store') }}">
			@csrf
			
			@include('backend.role.form')

			<div class="text-right">
				<a href="{{ route('backend.role.index') }}" class="btn btn-secondary btn_form">Cancel</a>
				&nbsp;
				<button type="submit" class="btn btn_pink btn_form">Save</button>
			</div>
		</form>

	</div>
</div>
@endsection

resources/views/backend/role/edit.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<style>

</style>
@endpush

@section('content')
<div class="section-header">
	<h2>Edit Role & Permission</h2>
</div>

<div class="card">
	<div class="card-body">

		@include('layouts.errors')

		<form method="post" action="{{ route('backend.role.update', $role->id) }}">
			@csrf
			{{ method_field('PUT') }}
			
			@include('backend.role.form')

			<div class="text-right">
				<a href="{{ route('backend.role.index') }}" class="btn btn-secondary btn_form">Cancel</a>
				&nbsp;
				<button type="submit" class="btn btn_pink btn_form">Save</button>
			</div>
		</form>

	</div>
</div>
@endsection

resources/views/backend/role/form.blade.php
@push('add_css')
<style>
.label_status label{margin:0;}
#tb_main th,
#tb_main td{text-align:center;}
#tb_main tr th:first-child,
#tb_main tr td:first-child{text-align:left;}
</style>
@endpush

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Role Name : <span class="req">*</span></label>
	<div class="col-sm-10">
    	<input type="text" name="name" class="form-control" value="{{ @$role->name }}" {{ @$role->id? 'disabled':'' }}>
    </div>
</div>


<div class="form-group row">
	<label class="col-sm-2 col-form-label">Permission : <span class="req">*</span></label>
	<div class="col-sm-10">
		<div class="table-responsive">
			<table id="tb_main" class="table table-bordered table-hover">
				<thead>
					<tr>
						<th>Menu</th>
						<th><i class="fa fa-eye"></i> View</th>
						<th><i class="fa fa-plus"></i> Add</th>
						<th><i class="fa fa-edit"></i> Edit</th>
						<th><i class="fa fa-trash"></i> Delete</th>
					</tr>
				</thead>
				
				<tbody>
				<?php
				$menus = \App\Menu::orderBy('sort', 'asc')->get();

				$p = new \App\Perm;
				foreach( $menus as $menu ){

					$can_view = '';
					$can_create = '';
					$can_edit = '';
					$can_delete = '';

					if( @$role->id ){
						$can = $p->where('role_id', $role->id)
								->where('menu_id', $menu->id)
								->first();

						if( @$can->can_view == 1 ) $can_view = 'checked';
						if( @$can->can_create == 1 ) $can_create = 'checked';
						if( @$can->can_edit == 1 ) $can_edit = 'checked';
						if( @$can->can_delete == 1 ) $can_delete = 'checked';
					}
					

					echo "<tr>";
					echo 	"<td>".$menu->name."</td>";
					echo 	"<td><input type='checkbox' name='can_view[".$menu->id."]' ".$can_view."></td>";
					echo 	"<td><input type='checkbox' name='can_create[".$menu->id."]' ".$can_create."></td>";
					echo 	"<td><input type='checkbox' name='can_edit[".$menu->id."]' ".$can_edit."></td>";
					echo 	"<td><input type='checkbox' name='can_delete[".$menu->id."]' ".$can_delete."></td>";
					echo "</tr>";
				}
				?>

				@if( !@$role->id )
					<?php
					// $p = new \App\Perm;
					// foreach( $menus as $menu ){

						// $can_view
					?>
					<!-- <tr>
						<td>{{ $menu->name }}</td>
						<td>
							<input type="checkbox" name="can_view[{{ $menu->id }}]">
						</td>
						<td>
							<input type="checkbox" name="can_create[{{ $menu->id }}]">
						</td>
						<td>
							<input type="checkbox" name="can_edit[{{ $menu->id }}]">
						</td>
						<td>
							<input type="checkbox" name="can_delete[{{ $menu->id }}]">
						</td>
					</tr> -->
					<?php
					// }
					?>
				@else

					<?php
					foreach( $role_perm as $perm ){
					?>
						<!-- <tr>
							<td>{{ $perm->menu->name }}</td>
							<td>
								<input type="checkbox" name="can_view[{{ $perm->id }}]" {{ $perm->can_view==1?'checked':'' }}>
							</td>
							<td>
								<input type="checkbox" name="can_create[{{ $perm->id }}]" {{ $perm->can_create==1?'checked':'' }}>
							</td>
							<td>
								<input type="checkbox" name="can_edit[{{ $perm->id }}]" {{ $perm->can_edit==1?'checked':'' }}>
							</td>
							<td>
								<input type="checkbox" name="can_delete[{{ $perm->id }}]" {{ $perm->can_delete==1?'checked':'' }}>
							</td>
						</tr> -->
					<?php
					}
					?>
				@endif
				</tbody>


			</table>
		</div>
	</div>
</div>



<!-- Super Admin Cannot Disable -->

@if( @$role->id != config('app.sa_id') )
<div class="form-group row label_status">
	<label class="col-sm-2 col-form-label">Status : </label>
	<div class="col-sm-10">
		<?php
		$checked = 1;
		if( isset($role->status) && $role->status == 0 )
			$checked = 0;
		?>
    	<label>
    		<input type="radio" name="status" value="1" {{ $checked==1? 'checked':'' }}>
    		Enable
    	</label>
    	&nbsp;
    	<label>
    		<input type="radio" name="status" value="0" {{ $checked==0? 'checked':'' }}>
    		Disabled
    	</label>
    </div>
</div>
@else
<input type="radio" name="status" value="1" style="display:none !important;" checked>
@endif

resources/views/backend/role/index.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<style>

</style>
@endpush

@section('content')
<?php
$perms = \App\Perm::can();
// print_r($perms);
?>

<div class="section-header">
	<h2>
		Role & Permission
		<div class="pull-right">
			@if( $perms[11]->create )
			<a href="{{ route('backend.role.create') }}" class="btn btn-sm btn_pink"><i class="fa fa-plus"></i>&nbsp; Create Role</a>
			@endif
		</div>
	</h2>
</div>

<div class="card">
	<div class="card-body">

		@include('layouts.errors')

		<div class="table-responsive">
			<table id="tb_main" class="table table-hover table-bordered">
				<thead>
					<tr>
						<th>#</th>
						<th>Role name</th>
						<th>Status</th>
						<th>Modified date</th>
						<th>Action</th>
					</tr>
				</thead>

				<tbody>
					@if( count($roles) > 0 )
						<?php
						$run = 1;
						foreach( $roles as $role ){

							$parse = \Carbon\Carbon::parse($role->updated_at);

							if( $role->status == 1 )
								$status = "<span class='stat_success'>enable</span>";
							else
								$status = "<span class='stat_danger'>disable</span>";

							echo "<tr>";
							echo 	"<td>".$run."</td>";
							echo 	"<td>".$role->name."</td>";
							echo 	"<td>".$status."</td>";
							echo 	"<td>".$parse->format('d/m/Y H:i')."</td>";
							echo 	"<td>";

							if( $perms[11]->edit )
								echo 	"<a href='".route('backend.role.edit', $role->id)."' class='btn btn-warning btn-sm'><i class='fa fa-edit'></i></a>&nbsp;";

							if( $perms[11]->delete ){
								if( $role->id != config('app.sa_id') ){
									echo 		"<form method='post' action='".route('backend.role.destroy', $role->id)."' style='display:inline-block'>";
									echo 			csrf_field();
									echo 			"<input type='hidden' name='_method' value='DELETE'>";
		                			echo 			"<button type='button' class='btn btn-danger btn-sm btn_confirm_warning' data-title='Confirm Delete'><i class='fa fa-trash'></i></button>";
									echo 		"</form>";
								}
							}

							echo 	"</td>";
							echo "</tr>";

							$run++;
						}
						?>
					@else
						<tr>
							<td colspan=4 align=center>No Data</td>
						</tr>
					@endif
				</tbody>
			</table>
		</div>

	</div>
</div>

@endsection


@push('add_js')

@endpush