routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('test_xml', 'TestXmlController@index');
Route::get('test_export_word', 'TestXmlController@test_export_word');
Route::get('test_send_mail', 'TestXmlController@test_send_mail');




//********* Backend *********//
Route::prefix('backend')->group(function () {
	Route::name('backend.')->group(function () {

		Route::get('auth/login', 'Backend\AuthController@login')->name('auth.login');
		Route::post('auth/login', 'Backend\AuthController@login_submit')->name('auth.login_submit');
		Route::get('auth/logout', 'Backend\AuthController@logout')->name('auth.logout');

		Route::middleware(['CheckAdminLogin'])->group(function () {
		    Route::get('/', 'Backend\DashboardController@index')->name('index');
		    
		    Route::resource('user', 'Backend\UserController');
		    Route::resource('partner_org', 'Backend\PartnerOrganizeController');
		    Route::resource('partner', 'Backend\PartnerController');
		    Route::get('partner/list_api/{id}', 'Backend\PartnerController@list_api')->name('partner.list_api');
		    Route::resource('dbconn', 'Backend\DatabaseConnectionController');
		    Route::post('dbconn/test_connect', 'Backend\DatabaseConnectionController@test_connect')->name('dbconn.test_connect');
		    Route::post('dbconn/list_connection', 'Backend\DatabaseConnectionController@list_connection')->name('dbconn.list_connection');
		    Route::post('dbconn/connect_by_alias', 'Backend\DatabaseConnectionController@connect_by_alias')->name('dbconn.connect_by_alias');
		    Route::resource('rest', 'Backend\RestController');
		    Route::post('rest/update_firststep/{id}', 'Backend\RestController@update_firststep')->name('rest.update_firststep');
		    Route::get('rest/{id}/step/{step}', 'Backend\RestController@step')->name('rest.step');
		    Route::post('rest/step3_save/{id}', 'Backend\RestController@step3_save')->name('rest.step3_save');
		    Route::post('rest/step4_save/{id}', 'Backend\RestController@step4_save')->name('rest.step4_save');


		    Route::resource('apilog', 'Backend\ApiLogController');
		    Route::post('apilog/export_data/{type}', 'Backend\ApiLogController@export_data')->name('apilog.export_data');
		    Route::resource('systemlog', 'Backend\SystemLogController');
		    Route::post('systemlog/export_data/{type}', 'Backend\SystemLogController@export_data')->name('systemlog.export_data');
		    Route::resource('report', 'Backend\ReportController');
		    Route::post('report/export_data/{type}', 'Backend\ReportController@export_data')->name('report.export_data');
		    Route::resource('setting', 'Backend\SettingController');


		    /**** Setting Role, Permission ****/
		    Route::resource('role', 'Backend\RoleController');
		});
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname', 'lastname', 'email', 'organization', 'position', 'phone', 'address', 'status', 'role_id', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public $blank_password = '%&v*65';

    public function role()
    {
        return $this->hasOne('App\Role', 'id', 'role_id');
    }

}

app/Http/Controllers/Backend/ApiLogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\ApiLogDataTable;
use App\ApiLog;
use Auth;

class ApiLogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ApiLogDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[7]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'apilog',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.log.api_log');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $log = ApiLog::findOrFail($id);

        return view('backend.log.api_list_schema', compact('log'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function export_data(Request $request)
    {
        // print_r($request->all());exit;
        header("Content-type: text/csv");
        header("Content-Disposition: attachment; filename=file.csv");
        header("Pragma: no-cache");
        header("Expires: 0");

        $logs = ApiLog::select('api_log.id', 'api_log.ip', 'api_log.path', 'api_log.partner_name', 'api_log.agent', 'api_log.status_code', 'api_log.log_type', 'api_log.datetime_at', 'api_log.datetime_at as datetime_normal');

        if( $request->seach_name )
            $logs = $logs->where('api_log.path', 'LIKE', '%'.$request->seach_name.'%');
        if( $request->seach_partner )
            $logs = $logs->where('api_log.partner_name', 'LIKE', '%'.$request->seach_partner.'%');


        if( $request->not_status_200 == 1 )
            $logs = $logs->where('api_log.status_code', '!=', '200');

        if( $request->search_status )
            $logs = $logs->where('api_log.status_code', $request->search_status);

        if( $request->search_date_start && $request->search_date_end )
            $logs = $logs->whereBetween('api_log.datetime_at', [$request->search_date_start, $request->search_date_end]);
        else if( $request->search_date_start && !$request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '>', $request->search_date_start);
        else if( !$request->search_date_start && $request->search_date_end )
            $logs = $logs->where('api_log.datetime_at', '<', $request->search_date_end);


        $logs = $logs->orderBy('api_log.datetime_at', 'desc')
                    ->get();

        $columns = array('datetime', 'status code', 'ip', 'api', 'agent', 'partner', 'type');

        $file = fopen('php://output', 'w');
        fputcsv($file, $columns);

        foreach($logs as $log) {
            fputcsv($file, array($log->datetime_at, $log->status_code, $log->ip, $log->path, $log->agent, $log->partner_name, $log->log_type));
        }
        exit();
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\User;
use Auth;

class AuthController extends Controller
{
    public function login()
    {
    	// User::create([
     //        'name' => 'asdasdsa',
     //        'email' => 'test12@gmail.com',
     //        'password' => Hash::make('test1234'),
     //    ]);
    	return view('backend.auth.login');
    }

    public function login_submit(Request $request)
    {
    	$credentials = $request->only('email', 'password');
        
        if( Auth::attempt($credentials) )
        	return redirect()->route('backend.index');
        else
        	return redirect()->back()->with('danger', 'E-mail หรือ Password ไม่ถูกต้อง');
    }

    public function logout()
    {
    	Auth::logout();
    	return redirect()->route('backend.auth.login');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ApiLog;
use Auth;

class DashboardController extends Controller
{
    public function index()
    {
        // phpinfo();exit;
        $syslog = [
            'code' => 200,
            'type' => 'view',
            'path' => 'dashboard',
            'user_id' => Auth::user()->id,
        ];
        \App\SystemLog::save_log($syslog);

    	$log_pops = ApiLog::select('api_log.path', \DB::raw('count(*) as total'), 'api_log.api_name')
                        ->where('api_log.log_type', 'req')
    					->orderBy('total', 'desc')
                        ->groupBy('api_log.path', 'api_log.api_name')
    					->limit(5)
    					->get();
    	// return $log_pop;
        $log_errors = ApiLog::select('api_log.id', 'api_log.path', 'api_log.datetime_at', 'api_log.api_name')
                        ->where('api_log.log_type', 'res')
                        ->where('api_log.status_code', '!=', '200')
                        // ->groupBy('path')
                        ->orderBy('api_log.datetime_at', 'desc')
                        ->limit(5)
                        ->get();
        // return $log_errors;
        $report = ApiLog::select('api_log.path', 'api_log.api_name', \DB::raw('count(*) as total'))
                        ->where('api_log.log_type', 'req')
                        ->where('api_log.path', '!=', 'auth/login')
                        ->groupBy('api_log.path', 'api_log.api_name')
                        ->limit(20)
                        ->get();
        // return $report;

    	return view('backend.index', compact('log_pops', 'log_errors', 'report'));
    }
}

app/Http/Controllers/Backend/PartnerOrganizeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\PartnerOrganizeDataTable;
use App\ApiCategory;
use Auth;

class PartnerOrganizeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PartnerOrganizeDataTable $dataTable)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->view ){

            $syslog = [
                'code' => 401,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }else{

            $syslog = [
                'code' => 200,
                'type' => 'view',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);
        }

        return $dataTable->render('backend.partner_org.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->create ){

            $syslog = [
                'code' => 401,
                'type' => 'insert',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        return view('backend.partner_org.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $validatedData = $request->validate([
            'cat_name' => 'required|unique:api_category',
        ]);

        $cat = new ApiCategory;
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'insert',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Create partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->route('backend.partner_org.index')->with('message', 'Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $perms = \App\Perm::can();
        if( !$perms[9]->edit ){

            $syslog = [
                'code' => 401,
                'type' => 'update',
                'path' => 'partner_organization',
                'user_id' => Auth::user()->id,
            ];
            \App\SystemLog::save_log($syslog);

            return redirect()->route('backend.index')->with('warning', "You don't have Permission.");
        }

        $cat = ApiCategory::findOrFail($id);

        return view('backend.partner_org.edit', compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cat = ApiCategory::findOrFail($id);
        $cat->cat_name = $request->cat_name;
        $cat->status = $request->status;
        $cat->save();

        $syslog = [
            'code' => 200,
            'type' => 'update',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Update partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        return redirect()->back()->with('message', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat = ApiCategory::findOrFail($id);

        $syslog = [
            'code' => 200,
            'type' => 'delete',
            'path' => 'partner_organization',
            'ref_id' => $cat->id,
            'user_id' => Auth::user()->id,
            'txt_data'=> 'Delete partner organization : '.$cat->cat_name,
        ];
        \App\SystemLog::save_log($syslog);

        foreach( $cat->partner as $row ){
            $row->delete();
        }

        $cat->delete();

        return redirect()->route('backend.partner_org.index')->with('message', 'Deleted');
    }
}

resources/views/backend/user/create.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<style>

</style>
@endpush

@section('content')
<div class="section-header">
	<h2>Create User</h2>
</div>

<div class="card">
	<div class="card-body">

		@include('layouts.errors')

		<form method="post" action="{{ route('backend.user.store') }}">
			@csrf
			
			@include('backend.user.form')

			<div class="text-right">
				<a href="{{ route('backend.user.index') }}" class="btn btn-secondary btn_form">Cancel</a>
				&nbsp;
				<button type="submit" class="btn btn_pink btn_form">Save</button>
			</div>
		</form>

	</div>
</div>
@endsection

resources/views/backend/user/edit.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<style>

</style>
@endpush

@section('content')
<div class="section-header">
	<h2>Edit User</h2>
</div>

<div class="card">
	<div class="card-body">

		@include('layouts.errors')

		<form method="post" action="{{ route('backend.user.update', $user->id) }}">
			@csrf
			{{ method_field('PUT') }}
			
			@include('backend.user.form')

			<div class="text-right">
				<a href="{{ route('backend.user.index') }}" class="btn btn-secondary btn_form">Cancel</a>
				&nbsp;
				<button type="submit" class="btn btn_pink btn_form">Save</button>
			</div>
		</form>

	</div>
</div>
@endsection

resources/views/backend/user/form.blade.php
<div class="form-group row">
	<label class="col-sm-2 col-form-label">First Name : <span class="req">*</span></label>
	<div class="col-sm-10">
    	<input type="text" name="firstname" class="form-control" value="{{ old('firstname')?old('firstname'):@$user->firstname }}">
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Last Name :</label>
	<div class="col-sm-10">
    	<input type="text" name="lastname" class="form-control" value="{{ old('lastname')?old('lastname'):@$user->lastname }}">
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Email : <span class="req">*</span></label>
	<div class="col-sm-10">
    	<input type="email" name="email" class="form-control" value="{{ old('email')?old('email'):@$user->email }}" {{ @$user->id?'disabled':'' }}>
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Password : <span class="req">*</span></label>
	<div class="col-sm-10">
    	<input type="password" name="password" class="form-control alias_str" value="{{ @$user->id? $user->blank_password:'' }}">
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-10">
    	<span class="req">must be at least 6 characters long, characters a-z, A-Z, 0-9, Symbols</span>
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Confirm Password : <span class="req">*</span></label>
	<div class="col-sm-10">
    	<input type="password" name="password_confirmation" class="form-control alias_str">
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Organization :</label>
	<div class="col-sm-10">
    	<input type="text" name="organization" class="form-control" value="{{ old('organization')?old('organization'):@$user->organization }}">
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Position :</label>
	<div class="col-sm-10">
    	<input type="text" name="position" class="form-control" value="{{ old('position')?old('position'):@$user->position }}">
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Mobile/Tel :</label>
	<div class="col-sm-10">
    	<input type="text" name="phone" class="form-control" value="{{ old('phone')?old('phone'):@$user->phone }}">
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label">Address :</label>
	<div class="col-sm-10">
    	<textarea class="form-control" name="address">{{ old('address')?old('address'):@$user->address }}</textarea>
    </div>
</div>

<?php
$roles = \App\Role::all();
$select_role = old('role_id')?old('role_id'):@$user->role_id;
?>
<div class="form-group row">
	<label class="col-sm-2 col-form-label">Role : <span class="req">*</span></label>
	<div class="col-sm-10">
    	<select class="form-control" name="role_id">
    		<option value>Select Role</option>
            @foreach( $roles as $role )
            <option value="{{ $role->id }}" {{ $select_role==$role->id? 'selected':'' }}>{{ $role->name }}</option>
            @endforeach
    	</select>
    </div>
</div>

<?php
$select_role = old('status')?old('status'):@$user->status;
?>
<div class="form-group row">
	<label class="col-sm-2 col-form-label">Status :</label>
	<div class="col-sm-10">
    	<label>
    		<input type="radio" name="status" value="1" {{ $select_role==1? 'checked':'' }}>
    		Enable
    	</label>
		&nbsp; &nbsp; &nbsp;
    	<label>
    		<input type="radio" name="status" value="0" {{ $select_role==0? 'checked':'' }}>
    		disable
    	</label>
    </div>
</div>

resources/views/backend/user/index.blade.php
@extends("backend/layouts/backend")


@push('add_css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/css/dataTables.bootstrap.min.css') }}">
<style>
.dataTables_filter{display: none;}
</style>
@endpush

@section('content')
<?php
$perms = \App\Perm::can();
?>

<div class="section-header">
	<h2>
		User
		<div class="pull-right">
			@if( $perms[2]->create )
			<a href="{{ route('backend.user.create') }}" class="btn btn-sm btn_pink"><i class="fa fa-plus"></i>&nbsp; Create User</a>
			@endif
		</div>
	</h2>
</div>

<div class="card">
	<div class="card-body">

		@include('layouts.errors')

		<div class="row">
			<div class="col-md-3">
				<input type="text" class="form-control" id="seach_name" placeholder="Contact name">
			</div>

			<div class="col-md-3">
				<input type="text" class="form-control" id="seach_email" placeholder="Email">
			</div>
			
			<?php
			$roles = \App\Role::where('status', 1)->get();
			?>
			<div class="col-md-3">
				<select class="form-control" id="search_role">
					<option value>Select role</option>
					@foreach( $roles as $role )
					<option value="{{ $role->name }}">{{ $role->name }}</option>
					@endforeach
				</select>
			</div>

			<div class="col-md-3">
				<select class="form-control" id="search_status">
		            <option value=>Status</option>
		            <option value="1">Enable</option>
		            <option value="0">Disable</option>
		        </select>
			</div>
		</div>

		<div class="table-responsive">
			{!! $dataTable->table(['id'=> 'tb_main', 'class'=> 'table table-bordered table-hover wid100']) !!}
		</div>

	</div>
</div>

@endsection


@push('add_js')
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<!-- <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('../vendor/yajra/laravel-datatables-buttons/src/resources/assets/buttons.server-side.js') }}"></script> -->
{!! $dataTable->scripts() !!}
@endpush